services:
  spark-master:
    build: ./docker/spark-master
    container_name: spark-master
    hostname: spark-master
    ports:
      - 8080:8080
      - 7077:7077
    volumes:
      - spark-shared-storage:/opt/workspace
    networks:
      bigdata_net:
        ipv4_address: 10.10.10.100

  spark-worker1:
    build: ./docker/spark-worker
    container_name: spark-worker1
    hostname: spark-worker1
    depends_on:
      - spark-master
    ports:
      - 8081:8081
    volumes:
      - spark-shared-storage:/opt/workspace
    networks:
      bigdata_net:
        ipv4_address: 10.10.10.101

  spark-worker2:
    build: ./docker/spark-worker
    container_name: spark-worker2
    hostname: spark-worker2
    depends_on: 
      - spark-master
    ports:
      - 8082:8081
    volumes:
      - spark-shared-storage:/opt/workspace
    networks:
      bigdata_net:
        ipv4_address: 10.10.10.102

  jupyter:
    build: ./docker/jupyter
    container_name: jupyter
    hostname: jupyter
    ports:
      - 8888:8888
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      POSTGRES_DB: ${POSTGRES_DB:-tender}
    volumes:
      - spark-shared-storage:/opt/workspace
    networks:
      bigdata_net:
        ipv4_address: 10.10.10.150
      
  postgre:
    image: postgres:latest
    container_name: postgre
    hostname: postgre
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      POSTGRES_DB: ${POSTGRES_DB:-tender}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      bigdata_net:
        ipv4_address: 10.10.10.151

volumes:
  spark-shared-storage:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./spark-shared-storage
  postgres-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./docker-data/postgres-data
  pgadmin-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./docker-data/pgadmin-data

networks:
  bigdata_net:
    driver: bridge
    name: bigdata-network
    ipam:
      config:
        - subnet: 10.10.10.0/24
          gateway: 10.10.10.1
